version: 1
accounts:
- name: alice
  coins:
  - 1000000000stake
- name: bob
  coins:
  - 1000000000stake
client:
  openapi:
    path: docs/static/openapi.yml
faucet:
  name: bob
  coins:
  - 5stake
validators:
- name: alice
  bonded: 100000000stake
